In [1]:
import pandas as pd
from pandas import json_normalize
import json

Read countries

In [2]:
with open('data/country_list_2022.json','r') as f:
    data = json.loads(f.read())
    
countries = json_normalize(data, record_path =['data'])
countries.top()

AttributeError: 'DataFrame' object has no attribute 'top'

In [3]:
countries

,source,data
0,https://datahub.io/core/country-list,"{'Code': 'AF', 'Name': 'Afghanistan'}"
1,https://datahub.io/core/country-list,"{'Code': 'AX', 'Name': 'Ã…land Islands'}"
2,https://datahub.io/core/country-list,"{'Code': 'AL', 'Name': 'Albania'}"
3,https://datahub.io/core/country-list,"{'Code': 'DZ', 'Name': 'Algeria'}"
4,https://datahub.io/core/country-list,"{'Code': 'AS', 'Name': 'American Samoa'}"
5,https://datahub.io/core/country-list,"{'Code': 'AD', 'Name': 'Andorra'}"
6,https://datahub.io/core/country-list,"{'Code': 'AO', 'Name': 'Angola'}"
7,https://datahub.io/core/country-list,"{'Code': 'AI', 'Name': 'Anguilla'}"
8,https://datahub.io/core/country-list,"{'Code': 'AQ', 'Name': 'Antarctica'}"
9,https://datahub.io/core/country-list,"{'Code': 'AG', 'Name': 'Antigua and Barbuda'}"
10,https://datahub.io/core/country-list,"{'Code': 'AR', 'Name': 'Argentina'}"
11,https://datahub.io/core/country-list,"{'Code': 'AM', 'Name': 'Armenia'}"
12,https://datahub.io/core/country-list,"{'Code': 'AW', 'Name': 'Aruba'}"
13,https://datahub.io/core/country-list,"{'Code': 'AU', 'Name': 'Australia'}"
14,https://datahub.io/core/country-list,"{'Code': 'AT', 'Name': 'Austria'}"
15,https://datahub.io/core/country-list,"{'Code': 'AZ', 'Name': 'Azerbaijan'}"
16,https://datahub.io/core/country-list,"{'Code': 'BS', 'Name': 'Bahamas'}"
17,https://datahub.io/core/country-list,"{'Code': 'BH', 'Name': 'Bahrain'}"
18,https://datahub.io/core/country-list,"{'Code': 'BD', 'Name': 'Bangladesh'}"
19,https://datahub.io/core/country-list,"{'Code': 'BB', 'Name': 'Barbados'}"
20,https://datahub.io/core/country-list,"{'Code': 'BY', 'Name': 'Belarus'}"
21,https://datahub.io/core/country-list,"{'Code': 'BE', 'Name': 'Belgium'}"
22,https://datahub.io/core/country-list,"{'Code': 'BZ', 'Name': 'Belize'}"
23,https://datahub.io/core/country-list,"{'Code': 'BJ', 'Name': 'Benin'}"
24,https://datahub.io/core/country-list,"{'Code': 'BM', 'Name': 'Bermuda'}"
25,https://datahub.io/core/country-list,"{'Code': 'BT', 'Name': 'Bhutan'}"
26,https://datahub.io/core/country-list,"{'Code': 'BO', 'Name': 'Bolivia, Plurinational..."
27,https://datahub.io/core/country-list,"{'Code': 'BQ', 'Name': 'Bonaire, Sint Eustatiu..."
28,https://datahub.io/core/country-list,"{'Code': 'BA', 'Name': 'Bosnia and Herzegovina'}"
29,https://datahub.io/core/country-list,"{'Code': 'BW', 'Name': 'Botswana'}"
...,...,...
219,https://datahub.io/core/country-list,"{'Code': 'TZ', 'Name': 'Tanzania, United Repub..."
220,https://datahub.io/core/country-list,"{'Code': 'TH', 'Name': 'Thailand'}"
221,https://datahub.io/core/country-list,"{'Code': 'TL', 'Name': 'Timor-Leste'}"
222,https://datahub.io/core/country-list,"{'Code': 'TG', 'Name': 'Togo'}"
223,https://datahub.io/core/country-list,"{'Code': 'TK', 'Name': 'Tokelau'}"
224,https://datahub.io/core/country-list,"{'Code': 'TO', 'Name': 'Tonga'}"
225,https://datahub.io/core/country-list,"{'Code': 'TT', 'Name': 'Trinidad and Tobago'}"
226,https://datahub.io/core/country-list,"{'Code': 'TN', 'Name': 'Tunisia'}"
227,https://datahub.io/core/country-list,"{'Code': 'TR', 'Name': 'Turkey'}"
228,https://datahub.io/core/country-list,"{'Code': 'TM', 'Name': 'Turkmenistan'}"
229,https://datahub.io/core/country-list,"{'Code': 'TC', 'Name': 'Turks and Caicos Islan..."
230,https://datahub.io/core/country-list,"{'Code': 'TV', 'Name': 'Tuvalu'}"
231,https://datahub.io/core/country-list,"{'Code': 'UG', 'Name': 'Uganda'}"
232,https://datahub.io/core/country-list,"{'Code': 'UA', 'Name': 'Ukraine'}"
233,https://datahub.io/core/country-list,"{'Code': 'AE', 'Name': 'United Arab Emirates'}"
234,https://datahub.io/core/country-list,"{'Code': 'GB', 'Name': 'United Kingdom'}"
235,https://datahub.io/core/country-list,"{'Code': 'US', 'Name': 'United States'}"
236,https://datahub.io/core/country-list,"{'Code': 'UM', 'Name': 'United States Minor Ou..."
237,https://datahub.io/core/country-list,"{'Code': 'UY', 'Name': 'Uruguay'}"
238,https://datahub.io/core/country-list,"{'Code': 'UZ', 'Name': 'Uzbekistan'}"
239,https://datahub.io/core/country-list,"{'Code': 'VU', 'Name': 'Vanuatu'}"
240,https://datahub.io/core/country-list,"{'Code': 'VE', 'Name': 'Venezuela, Bolivarian ..."
241,https://datahub.io/core/country-list,"{'Code': 'VN', 'Name': 'Viet Nam'}"
242,https://datahub.io/core/country-list,"{'Code': 'VG', 'Name': 'Virgin Islands, British'}"
243,https://datahub.io/core/country-list,"{'Code': 'VI', 'Name': 'Virgin Islands, U.S.'}"
244,https://datahub.io/core/country-list,"{'Code': 'WF', 'Name': 'Wallis and Futuna'}"
245,https://datahub.io/core/country-list,"{'Code': 'EH', 'Name': 'Western Sahara'}"
246,https://datahub.io/core/country-list,"{'Code': 'YE', 'Name': 'Yemen'}"
247,https://datahub.io/core/country-list,"{'Code': 'ZM', 'Name': 'Zambia'}"
248,https://datahub.io/core/country-list,"{'Code': 'ZW', 'Name': 'Zimbabwe'}"